spring.application.name=hrms-view

spring.datasource.url = jdbc:mysql://10.50.81.4:3306/hrms_bre
spring.datasource.username = emipodutdb01admin
spring.datasource.password = J@rv!s@6789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.data-source-properties.logSql=true

server.servlet.session.timeout=2m
spring.main.allow-bean-definition-overriding=true

#setting max life time for DB
spring.datasource.hikari.max-lifetime=100000

#multipart size limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#trust store location
http.client.ssl.trust-store=classpath:keystore/hrmsdecisionrulesview_bajajfinserv_in.p12
#trust store password
http.client.ssl.trust-store-password=PASSWORD
#removing whitelabel error message
server.error.whitelabel.enabled=false

excel.validation=&'+<()@,=>/|_"{}`:.-
